/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as GameUniverseIdRouteImport } from './routes/game.$universeId'
import { Route as ParticipateUniverseIdRouteImport } from './routes/participate.$universeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GameUniverseIdRoute = GameUniverseIdRouteImport.update({
  id: '/game/$universeId',
  path: '/game/$universeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipateUniverseIdRoute = ParticipateUniverseIdRouteImport.update({
  id: '/participate/$universeId',
  path: '/participate/$universeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/game/$universeId': typeof GameUniverseIdRoute
  '/participate/$universeId': typeof ParticipateUniverseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/game/$universeId': typeof GameUniverseIdRoute
  '/participate/$universeId': typeof ParticipateUniverseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/game/$universeId': typeof GameUniverseIdRoute
  '/participate/$universeId': typeof ParticipateUniverseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/game/$universeId' | '/participate/$universeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/game/$universeId' | '/participate/$universeId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/game/$universeId'
    | '/participate/$universeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  GameUniverseIdRoute: typeof GameUniverseIdRoute
  ParticipateUniverseIdRoute: typeof ParticipateUniverseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$universeId': {
      id: '/game/$universeId'
      path: '/game/$universeId'
      fullPath: '/game/$universeId'
      preLoaderRoute: typeof GameUniverseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participate/$universeId': {
      id: '/participate/$universeId'
      path: '/participate/$universeId'
      fullPath: '/participate/$universeId'
      preLoaderRoute: typeof ParticipateUniverseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  GameUniverseIdRoute: GameUniverseIdRoute,
  ParticipateUniverseIdRoute: ParticipateUniverseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
